### ISSUE TITLE
Publish

### ISSUE THREAD

**Issue by jacereda** [ollef/deriving-gcompare#1]
Could you publish this and rock in hackage? I'd like to try building sixten from nixpkgs and it would make things easier.

**Comment by ollef** [comment]
I noticed that there's already a package on Hackage that does what this library does, namely http://hackage.haskell.org/package/dependent-sum-template-0.0.0.6/, so I'm gonna give that a go and if it goes well deprecate this library in favour of it.

I'll publish rock on Hackage ASAP, I just want to write some docs and tests first.

**Comment by ollef** [comment]
[Rock is on hackage now](https://hackage.haskell.org/package/rock) and [Sixten depends on it](https://github.com/ollef/sixten/commit/40a04623e2637de127f82693788c6ab6833630fe).

Thanks for your patience.
